---
services:

  backend:
    image: soma1337/pipe_dream:latest
    volumes:
      - "./backend:/app"
    env_file:
      - "./backend/.env-$RTE"
    environment:
      - RTE=$RTE
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - dbnet
    restart: always

  postgres:
    image: postgres:16
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Remapped to avoid conflict with local postgres
    ports:
      - "5435:5432"
    env_file:
      - ".env"
    networks:
      - dbnet
    restart: always

volumes:
  postgres_data:

networks:
  dbnet:
    driver: bridge



    # build:
    #   context: ./backend
