name: CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -r backend/sqa-requirements.txt

      - name: Type-check with mypy
        working-directory: ./backend/src
        run: |
          mypy .
        continue-on-error: true

      - name: Lint with Pylint
        working-directory: ./backend/src
        run: |
          pylint .
        continue-on-error: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          latest_version=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)
          sudo curl -L "https://github.com/docker/compose/releases/download/$latest_version/docker-compose-$(uname -s)-$(uname -m)" \
          -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

          docker-compose --version

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_NAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Start Docker Compose services
        run: |
          RTE=test docker-compose up --abort-on-container-exit --exit-code-from backend

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:backend"
          push: true
          tags: soma1337/pipe_dream:latest
          cache-from: type=registry,ref=soma1337/pipe_dream:latest
          cache-to: type=inline

